#ifndef ZKP_Response_H
#define ZKP_Response_H

#include "Cloneable.h"

namespace ZKP
{

/*!
   \brief Base class for responses.

   Response objects generated by the Prover and sent to the Verifier.
 */
class Response:public Cloneable
{
public:
	Response() noexcept = default;

	virtual ~Response() = default;
};

}

#endif // ZKP_Response_H
